-- ============================================================================
-- Aceversity — seed data
-- Top 200 USA national universities (US News National Universities ranking order).
-- Idempotent: re-running updates ranking/location metadata without disturbing
-- any catalog discovery results already cached on the row.
-- ============================================================================

insert into public.colleges (rank, name, short_name, city, state, website_domain)
values
  (1, 'Princeton University', 'Princeton', 'Princeton', 'NJ', 'princeton.edu'),
  (2, 'Massachusetts Institute of Technology', 'MIT', 'Cambridge', 'MA', 'mit.edu'),
  (3, 'Harvard University', 'Harvard', 'Cambridge', 'MA', 'harvard.edu'),
  (4, 'Stanford University', 'Stanford', 'Stanford', 'CA', 'stanford.edu'),
  (5, 'Yale University', 'Yale', 'New Haven', 'CT', 'yale.edu'),
  (6, 'California Institute of Technology', 'Caltech', 'Pasadena', 'CA', 'caltech.edu'),
  (7, 'Duke University', 'Duke', 'Durham', 'NC', 'duke.edu'),
  (8, 'Johns Hopkins University', 'Johns Hopkins', 'Baltimore', 'MD', 'jhu.edu'),
  (9, 'Northwestern University', 'Northwestern', 'Evanston', 'IL', 'northwestern.edu'),
  (10, 'University of Pennsylvania', 'Penn', 'Philadelphia', 'PA', 'upenn.edu'),
  (11, 'Cornell University', 'Cornell', 'Ithaca', 'NY', 'cornell.edu'),
  (12, 'University of Chicago', 'UChicago', 'Chicago', 'IL', 'uchicago.edu'),
  (13, 'Brown University', 'Brown', 'Providence', 'RI', 'brown.edu'),
  (14, 'Columbia University', 'Columbia', 'New York', 'NY', 'columbia.edu'),
  (15, 'Dartmouth College', 'Dartmouth', 'Hanover', 'NH', 'dartmouth.edu'),
  (16, 'University of California, Los Angeles', 'UCLA', 'Los Angeles', 'CA', 'ucla.edu'),
  (17, 'University of California, Berkeley', 'UC Berkeley', 'Berkeley', 'CA', 'berkeley.edu'),
  (18, 'Rice University', 'Rice', 'Houston', 'TX', 'rice.edu'),
  (19, 'University of Notre Dame', 'Notre Dame', 'Notre Dame', 'IN', 'nd.edu'),
  (20, 'Vanderbilt University', 'Vanderbilt', 'Nashville', 'TN', 'vanderbilt.edu'),
  (21, 'Carnegie Mellon University', 'CMU', 'Pittsburgh', 'PA', 'cmu.edu'),
  (22, 'University of Michigan-Ann Arbor', 'Michigan', 'Ann Arbor', 'MI', 'umich.edu'),
  (23, 'Washington University in St. Louis', 'WashU', 'St. Louis', 'MO', 'wustl.edu'),
  (24, 'Emory University', 'Emory', 'Atlanta', 'GA', 'emory.edu'),
  (25, 'Georgetown University', 'Georgetown', 'Washington', 'DC', 'georgetown.edu'),
  (26, 'University of Virginia', 'UVA', 'Charlottesville', 'VA', 'virginia.edu'),
  (27, 'University of North Carolina at Chapel Hill', 'UNC', 'Chapel Hill', 'NC', 'unc.edu'),
  (28, 'University of Southern California', 'USC', 'Los Angeles', 'CA', 'usc.edu'),
  (29, 'University of California, San Diego', 'UC San Diego', 'La Jolla', 'CA', 'ucsd.edu'),
  (30, 'New York University', 'NYU', 'New York', 'NY', 'nyu.edu'),
  (31, 'University of Florida', 'UF', 'Gainesville', 'FL', 'ufl.edu'),
  (32, 'The University of Texas at Austin', 'UT Austin', 'Austin', 'TX', 'utexas.edu'),
  (33, 'Georgia Institute of Technology', 'Georgia Tech', 'Atlanta', 'GA', 'gatech.edu'),
  (34, 'University of California, Davis', 'UC Davis', 'Davis', 'CA', 'ucdavis.edu'),
  (35, 'University of California, Irvine', 'UC Irvine', 'Irvine', 'CA', 'uci.edu'),
  (36, 'University of Illinois Urbana-Champaign', 'UIUC', 'Urbana', 'IL', 'illinois.edu'),
  (37, 'Boston College', 'BC', 'Chestnut Hill', 'MA', 'bc.edu'),
  (38, 'Tufts University', 'Tufts', 'Medford', 'MA', 'tufts.edu'),
  (39, 'University of California, Santa Barbara', 'UCSB', 'Santa Barbara', 'CA', 'ucsb.edu'),
  (40, 'University of Wisconsin-Madison', 'UW-Madison', 'Madison', 'WI', 'wisc.edu'),
  (41, 'Boston University', 'BU', 'Boston', 'MA', 'bu.edu'),
  (42, 'The Ohio State University', 'Ohio State', 'Columbus', 'OH', 'osu.edu'),
  (43, 'Rutgers University-New Brunswick', 'Rutgers', 'New Brunswick', 'NJ', 'rutgers.edu'),
  (44, 'University of Maryland, College Park', 'UMD', 'College Park', 'MD', 'umd.edu'),
  (45, 'University of Rochester', 'Rochester', 'Rochester', 'NY', 'rochester.edu'),
  (46, 'Lehigh University', 'Lehigh', 'Bethlehem', 'PA', 'lehigh.edu'),
  (47, 'Purdue University', 'Purdue', 'West Lafayette', 'IN', 'purdue.edu'),
  (48, 'University of Georgia', 'UGA', 'Athens', 'GA', 'uga.edu'),
  (49, 'University of Washington', 'UW', 'Seattle', 'WA', 'washington.edu'),
  (50, 'Wake Forest University', 'Wake Forest', 'Winston-Salem', 'NC', 'wfu.edu'),
  (51, 'Case Western Reserve University', 'Case Western', 'Cleveland', 'OH', 'case.edu'),
  (52, 'Texas A&M University', 'Texas A&M', 'College Station', 'TX', 'tamu.edu'),
  (53, 'University of Minnesota, Twin Cities', 'Minnesota', 'Minneapolis', 'MN', 'umn.edu'),
  (54, 'Virginia Tech', 'Virginia Tech', 'Blacksburg', 'VA', 'vt.edu'),
  (55, 'Florida State University', 'FSU', 'Tallahassee', 'FL', 'fsu.edu'),
  (56, 'Northeastern University', 'Northeastern', 'Boston', 'MA', 'northeastern.edu'),
  (57, 'University of Massachusetts Amherst', 'UMass Amherst', 'Amherst', 'MA', 'umass.edu'),
  (58, 'Pennsylvania State University', 'Penn State', 'University Park', 'PA', 'psu.edu'),
  (59, 'University of Miami', 'Miami', 'Coral Gables', 'FL', 'miami.edu'),
  (60, 'Rensselaer Polytechnic Institute', 'RPI', 'Troy', 'NY', 'rpi.edu'),
  (61, 'University of Connecticut', 'UConn', 'Storrs', 'CT', 'uconn.edu'),
  (62, 'University of Pittsburgh', 'Pitt', 'Pittsburgh', 'PA', 'pitt.edu'),
  (63, 'Santa Clara University', 'Santa Clara', 'Santa Clara', 'CA', 'scu.edu'),
  (64, 'Binghamton University', 'Binghamton', 'Binghamton', 'NY', 'binghamton.edu'),
  (65, 'Indiana University Bloomington', 'IU Bloomington', 'Bloomington', 'IN', 'indiana.edu'),
  (66, 'Michigan State University', 'Michigan State', 'East Lansing', 'MI', 'msu.edu'),
  (67, 'Stony Brook University', 'Stony Brook', 'Stony Brook', 'NY', 'stonybrook.edu'),
  (68, 'Syracuse University', 'Syracuse', 'Syracuse', 'NY', 'syracuse.edu'),
  (69, 'Tulane University', 'Tulane', 'New Orleans', 'LA', 'tulane.edu'),
  (70, 'Brandeis University', 'Brandeis', 'Waltham', 'MA', 'brandeis.edu'),
  (71, 'Colorado School of Mines', 'Mines', 'Golden', 'CO', 'mines.edu'),
  (72, 'Pepperdine University', 'Pepperdine', 'Malibu', 'CA', 'pepperdine.edu'),
  (73, 'Rochester Institute of Technology', 'RIT', 'Rochester', 'NY', 'rit.edu'),
  (74, 'Worcester Polytechnic Institute', 'WPI', 'Worcester', 'MA', 'wpi.edu'),
  (75, 'University of California, Merced', 'UC Merced', 'Merced', 'CA', 'ucmerced.edu'),
  (76, 'Clemson University', 'Clemson', 'Clemson', 'SC', 'clemson.edu'),
  (77, 'Gonzaga University', 'Gonzaga', 'Spokane', 'WA', 'gonzaga.edu'),
  (78, 'Southern Methodist University', 'SMU', 'Dallas', 'TX', 'smu.edu'),
  (79, 'University of California, Riverside', 'UC Riverside', 'Riverside', 'CA', 'ucr.edu'),
  (80, 'Villanova University', 'Villanova', 'Villanova', 'PA', 'villanova.edu'),
  (81, 'North Carolina State University', 'NC State', 'Raleigh', 'NC', 'ncsu.edu'),
  (82, 'American University', 'American', 'Washington', 'DC', 'american.edu'),
  (83, 'Baylor University', 'Baylor', 'Waco', 'TX', 'baylor.edu'),
  (84, 'Loyola Marymount University', 'LMU', 'Los Angeles', 'CA', 'lmu.edu'),
  (85, 'University of Delaware', 'Delaware', 'Newark', 'DE', 'udel.edu'),
  (86, 'Marquette University', 'Marquette', 'Milwaukee', 'WI', 'marquette.edu'),
  (87, 'University of Illinois Chicago', 'UIC', 'Chicago', 'IL', 'uic.edu'),
  (88, 'University at Buffalo', 'UB', 'Buffalo', 'NY', 'buffalo.edu'),
  (89, 'Stevens Institute of Technology', 'Stevens', 'Hoboken', 'NJ', 'stevens.edu'),
  (90, 'University of Colorado Boulder', 'CU Boulder', 'Boulder', 'CO', 'colorado.edu'),
  (91, 'Fordham University', 'Fordham', 'Bronx', 'NY', 'fordham.edu'),
  (92, 'Howard University', 'Howard', 'Washington', 'DC', 'howard.edu'),
  (93, 'Texas Christian University', 'TCU', 'Fort Worth', 'TX', 'tcu.edu'),
  (94, 'University of Arizona', 'Arizona', 'Tucson', 'AZ', 'arizona.edu'),
  (95, 'University of California, Santa Cruz', 'UC Santa Cruz', 'Santa Cruz', 'CA', 'ucsc.edu'),
  (96, 'University of Utah', 'Utah', 'Salt Lake City', 'UT', 'utah.edu'),
  (97, 'Yeshiva University', 'Yeshiva', 'New York', 'NY', 'yu.edu'),
  (98, 'George Washington University', 'GW', 'Washington', 'DC', 'gwu.edu'),
  (99, 'University of Denver', 'Denver', 'Denver', 'CO', 'du.edu'),
  (100, 'University of Iowa', 'Iowa', 'Iowa City', 'IA', 'uiowa.edu'),
  (101, 'University of South Florida', 'USF', 'Tampa', 'FL', 'usf.edu'),
  (102, 'Auburn University', 'Auburn', 'Auburn', 'AL', 'auburn.edu'),
  (103, 'Brigham Young University', 'BYU', 'Provo', 'UT', 'byu.edu'),
  (104, 'University of Tennessee, Knoxville', 'Tennessee', 'Knoxville', 'TN', 'utk.edu'),
  (105, 'University of Nebraska-Lincoln', 'Nebraska', 'Lincoln', 'NE', 'unl.edu'),
  (106, 'Rutgers University-Newark', 'Rutgers-Newark', 'Newark', 'NJ', 'newark.rutgers.edu'),
  (107, 'University of Missouri', 'Mizzou', 'Columbia', 'MO', 'missouri.edu'),
  (108, 'Creighton University', 'Creighton', 'Omaha', 'NE', 'creighton.edu'),
  (109, 'Arizona State University', 'ASU', 'Tempe', 'AZ', 'asu.edu'),
  (110, 'Clark University', 'Clark', 'Worcester', 'MA', 'clarku.edu'),
  (111, 'Drexel University', 'Drexel', 'Philadelphia', 'PA', 'drexel.edu'),
  (112, 'Michigan Technological University', 'Michigan Tech', 'Houghton', 'MI', 'mtu.edu'),
  (113, 'University of Oregon', 'Oregon', 'Eugene', 'OR', 'uoregon.edu'),
  (114, 'University at Albany', 'UAlbany', 'Albany', 'NY', 'albany.edu'),
  (115, 'Miami University', 'Miami (Ohio)', 'Oxford', 'OH', 'miamioh.edu'),
  (116, 'Temple University', 'Temple', 'Philadelphia', 'PA', 'temple.edu'),
  (117, 'University of Kansas', 'KU', 'Lawrence', 'KS', 'ku.edu'),
  (118, 'University of South Carolina', 'South Carolina', 'Columbia', 'SC', 'sc.edu'),
  (119, 'Colorado State University', 'Colorado State', 'Fort Collins', 'CO', 'colostate.edu'),
  (120, 'The University of Alabama', 'Alabama', 'Tuscaloosa', 'AL', 'ua.edu'),
  (121, 'Illinois Institute of Technology', 'Illinois Tech', 'Chicago', 'IL', 'iit.edu'),
  (122, 'New Jersey Institute of Technology', 'NJIT', 'Newark', 'NJ', 'njit.edu'),
  (123, 'Saint Louis University', 'SLU', 'St. Louis', 'MO', 'slu.edu'),
  (124, 'University of Kentucky', 'Kentucky', 'Lexington', 'KY', 'uky.edu'),
  (125, 'University of Vermont', 'UVM', 'Burlington', 'VT', 'uvm.edu'),
  (126, 'Loyola University Chicago', 'Loyola Chicago', 'Chicago', 'IL', 'luc.edu'),
  (127, 'Seton Hall University', 'Seton Hall', 'South Orange', 'NJ', 'shu.edu'),
  (128, 'University of Oklahoma', 'Oklahoma', 'Norman', 'OK', 'ou.edu'),
  (129, 'Washington State University', 'Washington State', 'Pullman', 'WA', 'wsu.edu'),
  (130, 'Duquesne University', 'Duquesne', 'Pittsburgh', 'PA', 'duq.edu'),
  (131, 'University of Arkansas', 'Arkansas', 'Fayetteville', 'AR', 'uark.edu'),
  (132, 'Oregon State University', 'Oregon State', 'Corvallis', 'OR', 'oregonstate.edu'),
  (133, 'Rutgers University-Camden', 'Rutgers-Camden', 'Camden', 'NJ', 'camden.rutgers.edu'),
  (134, 'Chapman University', 'Chapman', 'Orange', 'CA', 'chapman.edu'),
  (135, 'DePaul University', 'DePaul', 'Chicago', 'IL', 'depaul.edu'),
  (136, 'Iowa State University', 'Iowa State', 'Ames', 'IA', 'iastate.edu'),
  (137, 'University of Cincinnati', 'Cincinnati', 'Cincinnati', 'OH', 'uc.edu'),
  (138, 'Florida International University', 'FIU', 'Miami', 'FL', 'fiu.edu'),
  (139, 'George Mason University', 'George Mason', 'Fairfax', 'VA', 'gmu.edu'),
  (140, 'University of Central Florida', 'UCF', 'Orlando', 'FL', 'ucf.edu'),
  (141, 'Ohio University', 'Ohio', 'Athens', 'OH', 'ohio.edu'),
  (142, 'University of New Hampshire', 'UNH', 'Durham', 'NH', 'unh.edu'),
  (143, 'University of Alabama at Birmingham', 'UAB', 'Birmingham', 'AL', 'uab.edu'),
  (144, 'Texas Tech University', 'Texas Tech', 'Lubbock', 'TX', 'ttu.edu'),
  (145, 'University of Dayton', 'Dayton', 'Dayton', 'OH', 'udayton.edu'),
  (146, 'Rowan University', 'Rowan', 'Glassboro', 'NJ', 'rowan.edu'),
  (147, 'University of St. Thomas', 'St. Thomas', 'St. Paul', 'MN', 'stthomas.edu'),
  (148, 'Clarkson University', 'Clarkson', 'Potsdam', 'NY', 'clarkson.edu'),
  (149, 'Hofstra University', 'Hofstra', 'Hempstead', 'NY', 'hofstra.edu'),
  (150, 'Mercer University', 'Mercer', 'Macon', 'GA', 'mercer.edu'),
  (151, 'Missouri University of Science and Technology', 'Missouri S&T', 'Rolla', 'MO', 'mst.edu'),
  (152, 'University of Nevada, Reno', 'Nevada', 'Reno', 'NV', 'unr.edu'),
  (153, 'University of Rhode Island', 'URI', 'Kingston', 'RI', 'uri.edu'),
  (154, 'Louisiana State University', 'LSU', 'Baton Rouge', 'LA', 'lsu.edu'),
  (155, 'University of Mississippi', 'Ole Miss', 'University', 'MS', 'olemiss.edu'),
  (156, 'Kansas State University', 'K-State', 'Manhattan', 'KS', 'k-state.edu'),
  (157, 'Seattle University', 'Seattle U', 'Seattle', 'WA', 'seattleu.edu'),
  (158, 'Oklahoma State University', 'Oklahoma State', 'Stillwater', 'OK', 'okstate.edu'),
  (159, 'University of Idaho', 'Idaho', 'Moscow', 'ID', 'uidaho.edu'),
  (160, 'Ball State University', 'Ball State', 'Muncie', 'IN', 'bsu.edu'),
  (161, 'Bowling Green State University', 'BGSU', 'Bowling Green', 'OH', 'bgsu.edu'),
  (162, 'Kent State University', 'Kent State', 'Kent', 'OH', 'kent.edu'),
  (163, 'University of Louisville', 'Louisville', 'Louisville', 'KY', 'louisville.edu'),
  (164, 'University of Maine', 'Maine', 'Orono', 'ME', 'umaine.edu'),
  (165, 'University of Memphis', 'Memphis', 'Memphis', 'TN', 'memphis.edu'),
  (166, 'The University of Texas at Dallas', 'UT Dallas', 'Richardson', 'TX', 'utdallas.edu'),
  (167, 'Virginia Commonwealth University', 'VCU', 'Richmond', 'VA', 'vcu.edu'),
  (168, 'Augusta University', 'Augusta', 'Augusta', 'GA', 'augusta.edu'),
  (169, 'The Catholic University of America', 'Catholic', 'Washington', 'DC', 'catholic.edu'),
  (170, 'Central Michigan University', 'Central Michigan', 'Mount Pleasant', 'MI', 'cmich.edu'),
  (171, 'Illinois State University', 'Illinois State', 'Normal', 'IL', 'ilstu.edu'),
  (172, 'Indiana University Indianapolis', 'IU Indianapolis', 'Indianapolis', 'IN', 'indianapolis.iu.edu'),
  (173, 'Montana State University', 'Montana State', 'Bozeman', 'MT', 'montana.edu'),
  (174, 'New Mexico State University', 'NMSU', 'Las Cruces', 'NM', 'nmsu.edu'),
  (175, 'Northern Arizona University', 'NAU', 'Flagstaff', 'AZ', 'nau.edu'),
  (176, 'Old Dominion University', 'ODU', 'Norfolk', 'VA', 'odu.edu'),
  (177, 'Portland State University', 'Portland State', 'Portland', 'OR', 'pdx.edu'),
  (178, 'San Diego State University', 'SDSU', 'San Diego', 'CA', 'sdsu.edu'),
  (179, 'St. John''s University', 'St. John''s', 'Queens', 'NY', 'stjohns.edu'),
  (180, 'Texas State University', 'Texas State', 'San Marcos', 'TX', 'txstate.edu'),
  (181, 'University of Hawaii at Manoa', 'Hawaii', 'Honolulu', 'HI', 'hawaii.edu'),
  (182, 'University of Houston', 'Houston', 'Houston', 'TX', 'uh.edu'),
  (183, 'University of Missouri-Kansas City', 'UMKC', 'Kansas City', 'MO', 'umkc.edu'),
  (184, 'University of North Texas', 'UNT', 'Denton', 'TX', 'unt.edu'),
  (185, 'University of San Diego', 'USD', 'San Diego', 'CA', 'sandiego.edu'),
  (186, 'University of San Francisco', 'USF (SF)', 'San Francisco', 'CA', 'usfca.edu'),
  (187, 'The University of Texas at San Antonio', 'UTSA', 'San Antonio', 'TX', 'utsa.edu'),
  (188, 'University of Tulsa', 'Tulsa', 'Tulsa', 'OK', 'utulsa.edu'),
  (189, 'Wayne State University', 'Wayne State', 'Detroit', 'MI', 'wayne.edu'),
  (190, 'West Virginia University', 'WVU', 'Morgantown', 'WV', 'wvu.edu'),
  (191, 'Western Michigan University', 'Western Michigan', 'Kalamazoo', 'MI', 'wmich.edu'),
  (192, 'Quinnipiac University', 'Quinnipiac', 'Hamden', 'CT', 'qu.edu'),
  (193, 'University of Massachusetts Lowell', 'UMass Lowell', 'Lowell', 'MA', 'uml.edu'),
  (194, 'University of Massachusetts Boston', 'UMass Boston', 'Boston', 'MA', 'umb.edu'),
  (195, 'Georgia State University', 'Georgia State', 'Atlanta', 'GA', 'gsu.edu'),
  (196, 'University of Colorado Denver', 'CU Denver', 'Denver', 'CO', 'ucdenver.edu'),
  (197, 'University of Maryland, Baltimore County', 'UMBC', 'Baltimore', 'MD', 'umbc.edu'),
  (198, 'University of North Carolina at Charlotte', 'UNC Charlotte', 'Charlotte', 'NC', 'charlotte.edu'),
  (199, 'Utah State University', 'Utah State', 'Logan', 'UT', 'usu.edu'),
  (200, 'Mississippi State University', 'Mississippi State', 'Mississippi State', 'MS', 'msstate.edu')
on conflict (website_domain) do update set
  rank       = excluded.rank,
  name       = excluded.name,
  short_name = excluded.short_name,
  city       = excluded.city,
  state      = excluded.state;
