import type { Metadata } from 'next';
import Link from 'next/link';

import { ContentPage, Prose } from '@/components/layout/content-page';
import { SITE } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Terms of service',
  description: `The terms that govern your use of ${SITE.name}.`,
};

export default function TermsPage() {
  return (
    <ContentPage
      eyebrow="Legal"
      title="Terms of service"
      intro={`Last updated ${SITE.legalUpdated}`}
    >
      <Prose>
        <p>
          These terms govern your use of {SITE.name} (the “service”). By using the service you agree
          to them. If you do not agree, please do not use {SITE.name}.
        </p>

        <h2>1. Who can use the service</h2>
        <p>
          You must be at least 13 years old to use {SITE.name}. If you are under the age of majority
          where you live, you may use the service only with a parent or guardian’s permission.
        </p>

        <h2>2. Your account</h2>
        <p>
          You are responsible for activity on your account and for keeping access to your email
          secure, since sign-in links are sent there. Tell us promptly about any unauthorized use.
        </p>

        <h2>3. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            use the service for anything unlawful, or to cheat on graded coursework or exams in
            violation of your school’s rules;
          </li>
          <li>
            scrape, copy or resell the service or its content in bulk, or access it through
            automated means other than our published interfaces;
          </li>
          <li>
            interfere with the service, probe it for vulnerabilities without permission, or attempt
            to bypass usage limits;
          </li>
          <li>impersonate others or submit content that infringes someone else’s rights.</li>
        </ul>

        <h2>4. Course information and sources</h2>
        <p>
          {SITE.name} reads only publicly available university catalog pages. From them we store
          factual information about courses, such as titles, descriptions, topics and reading lists.
          We never copy or store copyrighted textbook or course-material content.
        </p>
        <p>
          Course details may be incomplete, out of date or misread. They are provided for general
          information only. Always confirm requirements, schedules and prerequisites with your
          university.
        </p>
        <p>
          {SITE.name} is independent and is not affiliated with, sponsored by or endorsed by any
          university. University names are used only to identify their courses.
        </p>

        <h2>5. AI-generated practice content</h2>
        <p>
          Practice questions and explanations are generated by AI and can contain errors. They are
          study aids, not official course material, and do not predict or reflect the content of any
          real exam. Use your judgment and your course materials.
        </p>

        <h2>6. Intellectual property</h2>
        <p>
          The service, including its design, software and branding, belongs to {SITE.name} and is
          protected by law. We grant you a personal, non-transferable, non-commercial licence to use
          the service and the practice content you generate for your own study.
        </p>

        <h2>7. Feedback</h2>
        <p>If you send us suggestions, we may use them without any obligation to you.</p>

        <h2>8. Suspension and termination</h2>
        <p>
          You may stop using the service at any time and ask us to delete your account. We may
          suspend or end access if you break these terms or if needed to protect the service or
          other users.
        </p>

        <h2>9. Disclaimers</h2>
        <p>
          The service is provided “as is” and “as available”, without warranties of any kind,
          express or implied, including fitness for a particular purpose, accuracy and
          non-infringement. We do not guarantee any academic result.
        </p>

        <h2>10. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, {SITE.name} will not be liable for any indirect,
          incidental, special or consequential damages, or for lost data or opportunities, arising
          from your use of the service. Our total liability for any claim is limited to the greater
          of the amount you paid us in the past 12 months or US$50.
        </p>

        <h2>11. Changes to these terms</h2>
        <p>
          We may update these terms. We will change the date above and, for material changes, give
          notice on the site or by email. Continuing to use the service means you accept the updated
          terms.
        </p>

        <h2>12. Governing law</h2>
        <p>
          These terms are governed by the laws of the United States and the state in which{' '}
          {SITE.name} is established, without regard to conflict-of-law rules.
        </p>

        <h2>13. Contact</h2>
        <p>
          Questions about these terms? Email{' '}
          <a href={`mailto:${SITE.emails.legal}`}>{SITE.emails.legal}</a> or use our{' '}
          <Link href="/contact">contact form</Link>. See also our{' '}
          <Link href="/privacy">privacy policy</Link>.
        </p>
      </Prose>
    </ContentPage>
  );
}
