import { LifeBuoy, Mail, MessageSquare } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';

import { ContentPage } from '@/components/layout/content-page';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { SITE } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Support',
  description: `Answers to common questions about ${SITE.name}.`,
};

const FAQ_GROUPS = [
  {
    title: 'Getting started',
    items: [
      {
        q: `Do I need an account to use ${SITE.name}?`,
        a: 'No account is needed to check whether a course is available. Browsing universities and courses, and generating or taking practice tests, needs a free account.',
      },
      {
        q: 'How do I sign in?',
        a: 'Enter your email on the sign-in page and we will send you a magic link. There is no password to remember — open the link on the same device to finish signing in.',
      },
      {
        q: 'I didn’t receive my sign-in email.',
        a: 'Check your spam or promotions folder and make sure the address is spelled correctly. Links expire after a short time, so request a new one if it has been a while. University email filters sometimes delay messages by a few minutes.',
      },
    ],
  },
  {
    title: 'Courses and catalogs',
    items: [
      {
        q: 'Where does the course information come from?',
        a: 'From each university’s own public course catalog. We read the catalog pages and organize what they say into a course profile.',
      },
      {
        q: 'My university or course is missing.',
        a: 'We cover top-ranked worldwide universities and add catalogs over time. Some catalogs are hard to read automatically. Send us the university name and a link to its catalog through the contact page and we will take a look.',
      },
      {
        q: 'Some course details look wrong or out of date.',
        a: 'Catalogs change every term and our reading of them is not perfect. Always confirm details with your university before you register. Let us know about the error — include the course number and the page link — and we will correct it.',
      },
    ],
  },
  {
    title: 'Practice tests',
    items: [
      {
        q: 'How are practice questions created?',
        a: 'Questions are generated by AI from the course profile, section by section. They are meant for practice and self-review and can occasionally contain mistakes.',
      },
      {
        q: 'Can I print a test?',
        a: 'Yes. Use your browser’s print option on a test page — navigation and other page chrome are hidden in the printed version.',
      },
      {
        q: 'Are these the questions on my real exam?',
        a: `No. ${SITE.name} has no access to your instructors’ exams. Practice questions are original and are not a substitute for your course materials.`,
      },
    ],
  },
  {
    title: 'Account and privacy',
    items: [
      {
        q: 'How do I delete my account or my data?',
        a: `Email ${SITE.emails.privacy} from the address you signed up with and we will delete your account and associated data.`,
      },
      {
        q: 'Do you sell my data?',
        a: 'No. See our privacy policy for exactly what we collect and why.',
      },
    ],
  },
];

export default function SupportPage() {
  return (
    <ContentPage
      eyebrow="Help center"
      title="How can we help?"
      intro="Answers to the questions we hear most. Can’t find yours? We’re a message away."
    >
      <div className="grid gap-4 sm:grid-cols-3">
        <SupportCard icon={Mail} title="Email support" href={`mailto:${SITE.emails.support}`}>
          {SITE.emails.support}
        </SupportCard>
        <SupportCard icon={MessageSquare} title="Contact form" href="/contact">
          Send us a message
        </SupportCard>
        <SupportCard icon={LifeBuoy} title="Response time" href="/contact">
          Usually within 2 business days
        </SupportCard>
      </div>

      <div className="mt-12 space-y-10">
        {FAQ_GROUPS.map((group) => (
          <section key={group.title}>
            <h2 className="text-primary mb-2 text-xl font-semibold">{group.title}</h2>
            <Accordion>
              {group.items.map((item) => (
                <AccordionItem key={item.q} value={item.q}>
                  <AccordionTrigger className="text-base">{item.q}</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground pb-2 leading-6">{item.a}</p>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </section>
        ))}
      </div>
    </ContentPage>
  );
}

function SupportCard({
  icon: Icon,
  title,
  href,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  href: string;
  children: React.ReactNode;
}) {
  return (
    <Link
      href={href}
      className="bg-card hover:border-primary/40 rounded-xl border p-4 transition-colors"
    >
      <Icon className="text-brand-teal mb-2 size-5" />
      <p className="font-semibold">{title}</p>
      <p className="text-muted-foreground mt-0.5 text-sm break-words">{children}</p>
    </Link>
  );
}
